"""recreated tables

Revision ID: 335abfaea85e
Revises: 
Create Date: 2023-09-29 09:07:36.177761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335abfaea85e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('lastname', sa.String(length=16), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=False),
    sa.Column('lastname', sa.String(length=16), nullable=False),
    sa.Column('age', sa.String(length=2), nullable=False),
    sa.Column('disabilityGrade', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child')
    op.drop_table('admins_users')
    # ### end Alembic commands ###
