"""child fields length changed

Revision ID: 9ba3c1da5ecd
Revises: c22c3eda74a1
Create Date: 2023-10-26 08:50:21.263934

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ba3c1da5ecd'
down_revision = 'c22c3eda74a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('lastname',
               existing_type=mysql.VARCHAR(length=16),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.alter_column('lastname',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
