"""Scores and Games models added

Revision ID: c22c3eda74a1
Revises: 335abfaea85e
Create Date: 2023-10-10 08:15:50.160057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22c3eda74a1'
down_revision = '335abfaea85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=16), nullable=False),
    sa.Column('id_game', sa.Integer(), nullable=False),
    sa.Column('id_child', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_child'], ['child.id'], ),
    sa.ForeignKeyConstraint(['id_game'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('games')
    # ### end Alembic commands ###
